// Array of jokes
const jokes = [
    "Schwartz is sitting in his room, wearing only a top hat, when Steinberg strolls in. 'Why are you sitting here naked?' 'It’s all right,' says Schwartz. 'Nobody comes to visit.' 'But why the hat?' 'Maybe somebody will come.'",
    "A woman on a train walked up to a man across the table. 'Excuse me,' she said, 'but are you Jewish?' 'No,' replied the man. A few minutes later the woman returned. 'Excuse me,' she said again, 'are you sure you’re not Jewish?' 'I’m sure,' said the man. But the woman was not convinced, and a few minutes later she approached him a third time. 'Are you absolutely sure you’re not Jewish?' she asked. 'All right, all right,' the man said. 'You win. I’m Jewish.' 'That’s funny,' said the woman. 'You don’t look Jewish.'",
    "Two men of Chelm went out for a walk, when suddenly it began to rain. 'Quick,' said one. 'Open your umbrella.' 'It won’t help,' said his friend. 'My umbrella is full of holes.' 'Then why did you bring it?' 'I didn’t think it would rain!'",
    "A group of five Jewish women are eating lunch in a busy cafe. Nervously, their waiter approaches the table. 'Ladies,' he says. 'Is anything okay?'",
    "A Jewish man is shipwrecked on a desert island. He’s stuck for years! Using materials from around the island, he builds a house, a store, and a synagogue. Eventually, he’s made a whole neighborhood. One day, he’s rescued by a passing ship. The sailors help him collect his few possessions and get ready to leave the island forever. Just before they leave, one of the sailors says, 'Hey! Why’d you build two synagogues?' The man rolls his eyes. 'This,' he says, pointing at one building, 'Is my synagogue.' 'And that,' he says, pointing at the other, 'Is the one I would never set foot in!'",
    "Three Jewish mothers are sitting on a bench, arguing over which one’s son loves her the most. The first one says, 'You know, my son sends me flowers every Shabbos.' 'You call that love?' says the second mother. 'My son calls me every day!' 'That’s nothing,' says the third woman. 'My son is in therapy five days a week. And the whole time, he talks about me!'",
    "A synagogue has a mice problem. The custodian tries traps, bait, mice, everything. Nothing works. Finally, he goes to the rabbi and explains the problem. 'I have the solution,' the rabbi says. 'Well, what is it?' says the custodian. 'It’s a foolproof plan,' the rabbi says, smiling. 'I’ll give them all Bar Mitzvahs — we’ll never see them again!'",
    "A group of people standing on a subway platform — an American, a Russian, and an Israeli. A reporter approaches and says, 'Excuse me, can I get your opinion about the meat shortage?' 'What’s a shortage?' says the American. 'What’s meat?' says the Russian. 'What’s excuse me?' says the Israeli.",
    "A rabbi is harboring a secret — she has always wanted to try pork. One night she drives across town to the furthest restaurant from her shul and orders an entire suckling pig. Just as the waiter sets down the full roast pig with an apple in its mouth, she sees a group of her congregants has walked in and is watching her, mouths open. The rabbi widens her eyes, 'So nu, what kind of place is this?' she says. 'You order an apple and look how it’s served!'",
    "An elderly Jewish man faints and is rushed to the nearest hospital. A nurse tucks him into bed and says, 'Mr. Schwartzman, are you comfortable?' Schwartzman replies, 'I make a living…!'",
    "A yeshiva decides to start a crew team. But no matter how much they practice, they lose every single race. Eventually they decide to send one boy down to the nearby prep school as a spy, to watch their winning crew team and find out what their secret is. After a day of reconnaissance, the boy comes back. 'Listen!' he tells his teammates. 'I learned how they do it — they have eight guys rowing, and only one guy screaming!'",
    "An old man is struck by a car and brought to the hospital. A nurse enters his room and says, 'Sir, are you comfortable?' The old man replies, 'I make a nice living.'",
    "A poor man walking in the forest feels close enough to God to ask, 'God, what is a million years to you?' God replies, 'My son, a million years to you is like a second to me.' The man asks, 'God, what is a million dollars to you?' God replies, 'My son, a million dollars to you is less than a penny to me. It means almost nothing to me.' The man asks, 'So God, can I have a million dollars?' And God replies, 'In a second.'",
    "Old Max Greenberg lies on his deathbed. He asks, ‘Is my wife Sara here?’ ‘Yes,’ says Sara. ‘I’m here with you!’ ‘Are my children here?’ ‘Yes, Max, your sons and your daughters are all here!’ ‘Are my grandchildren here?’ ‘Yes, all of the grandchildren are here. Max, your entire family is here with you!’ Then Max Greenberg lifts his head one last time and asks, ‘So why is the light on in the kitchen?’",
    "Shloime and Esty go on a big vacation all the way across the world to Thailand. They’re having a great time until one day they get into a fight. Shloime goes on a walk on the beach by himself to cool off. While walking, he looks down to see an old-fashioned oil lamp in the sand. He picks it up and, as he rubs off the sand, a genie appears. ‘My master,’ the genie says, ‘I can grant you one wish. Tell me what you want.’ Shloime pulls out his phone and shows the genie a map of Israel. ‘This is Israel. There’s always conflict there. Make peace between Israel and all its neighbors.’ ‘You think we haven’t heard of the Middle East peace problem? This is far too complicated for a simple wish. Ask me for something reasonable.’ Shloime thinks about his argument with Esty, his wife, and he says, ‘OK, my wish is to understand the mind of a woman.’ The genie looks at Shloime and says, ‘Show me that map again.’",
    "Morty Greenbaum shows up at the country club with his new wife, a beautiful woman half his age. His buddies are very impressed and later they ask him how he got such a gorgeous young wife. ‘I lied about my age,’ Morty confesses. They ask, ‘Did you tell her you were fifty?’ ‘No,’ replies Morty. ‘I told her I was ninety.’",
    "The Emperor of China needed a new Chief Samurai. He held tryouts and selected three finalists for the prestigious position. The first finalist was a samurai from the south. He stepped forward and opened a small box, releasing a fly. The samurai drew his samurai sword, sliced the air, and the fly, split perfectly in two, fell dead to the ground. The second finalist, a samurai from the north, came forward holding an even smaller box. He opened it and out flew a gnat. The samurai drew his sword, striked, and the gnat, split in two, fell dead to the ground. The third finalist was Shimmy Yankowitz from Crown Heights, Brooklyn, carrying an old cigar box. Shimmy opened the box and out flew a bumble bee. He took out a very thin sword, striked, and the bumble bee flew away. The emperor, annoyed, said, ‘What kind of skill is that? The bee did not die!’ Shimmy replied, ‘Of course not, sir. The circumcision is not intended to kill.’",
    "A rabbi, a priest, and a minister are playing poker when the cops raid the game. The lead officer questions the priest, ‘Father Murphy, were you gambling?’ Father Murphy silently asks God to forgive him for what he is about to say. ‘No, Officer. I was not gambling.’ The cop turns to the minister, ‘Pastor Johnson, were you gambling?’ Pastor Johnson also appeals to Heaven. ‘No, Officer. I was not gambling.’ The cop finally turns to the rabbi. ‘Rabbi Goldstein, were you gambling?’ ‘Gambling?’ he asks, glancing at the priest and the minister.  ‘With who?’",
    "Moshe, Avi, and Yitzi are walking up the fairway. Two of the guys are grumbling and complaining. Moshe says, ‘Do you know what I had to do so that I could come out and play golf with you fellas? I had to reorganize the whole garage and build shelves. It took forever.’ Avi says, ‘What are you complaining about? I had to build my wife a whole new kitchen so I could come out and play golf.’ Yitzi looks at them and says, ‘Amateurs! This morning at 5:30, my big alarm clock with the two bells went ‘Brrrrrrringggg!!’ I elbowed my wife and said ‘Honey, golf course or intercourse?’ She said, ‘Don’t forget your sweater.’’",
    "After services one Shabbat, Rabbi Cohen is approached by Larry Levy, the famous TV producer. ‘Rabbi Cohen, that sermon was amazing! I want to put you on my talk show on national TV.’ ‘Oh my, I’m so flattered,’ says the rabbi. ‘That would be wonderful!’ ‘Here’s the thing, Rabbi. TV audience attention spans are much smaller. You can’t do a 25 minute sermon on TV.’ ‘Oh, I see. Well, I could take away the opening anecdote about my trip to Brazil. That would chop it down by a few minutes – bring it down to 18 or 19 minutes.’ ‘Yeah, Rabbi, that’s still too long.’ ‘Instead of five examples of the teaching, I could do it with three. That would make it twelve minutes.’ ‘Now we’re cookin’, Rabbi, but it’s got to be shorter than that.’ ‘Well, really I just need one strong example. Beginning, middle, end, with a nice takeaway. I could do the whole sermon in five minutes flat.’ ‘So, Rabbi, why didn’t you?’",
    "Two Jews, Benny and Mayshe, are walking down the street and they pass a church. There’s a big sign that says ‘We’ll Pay You $1000 to Convert!’ Mayshe goes inside and comes out ten minutes later. Benny asks him, ‘So, did you get the thousand dollars?’ Mayshe replies, ‘Is that all you people think about, money??’",
    "A lady calls the Mount Sinai Funeral Home. ‘Hello, this is Esther Goldberg. My husband passed this morning. Please come and pick him up.’ ‘Oh, but Mrs. Goldberg,’ the funeral director replies, ‘we buried your husband last year.’ ‘Yes, I remarried.’ ‘Oh, Mazel Tov!’",
    "A rabbi and a minister become friends, meeting every year at an interfaith conference. One year, the minister says to the rabbi, ‘You guys are so good at fundraising. I’m really having trouble. The members of my church are just not donating enough.’ The rabbi says, ‘You’re approaching this all wrong. It’s all about the building fund. You’ve gotta have a building fund and then people will donate.’ The following year, they meet again. The minister tells the rabbi, ‘You were absolutely right. Donations for the building fund are pouring in. It’s fantastic! Thank you so much for that tip.’ Another year goes by and they meet yet again. The minister says, ‘It was good while it lasted, but we finished the building and now people are just not donating as much as they were.’ The rabbi replies, ‘You finished the building? Who told you to finish the building? You never finish the building!’",
    "Three men are sitting next to each other on a plane flying out of Texas: two big guys with cowboy hats and a little old Jewish man. They get to talking and one of the big fellas says, ‘I own a place. Thousand acres, thousand head of cattle. My name is Keith and I call it Circle K.’ The other big fella says, ‘I own a place, too. Ten thousand acres. Ten thousand heads of cattle. My name is John. I call it Big John’s’ The little old Jewish man says, ‘That’s very nice. I only own a hundred acres, no cattle. My name is Yitzi.’ John says, ‘Oh yea, Yitzi? What do you call your place?’ ‘Downtown Dallas.’",
    "A rabbi is walking down the street during Passover and he sees the synagogue president up ahead on the sidewalk. The rabbi rushes ahead to discuss some business, but before he can reach him, the president enters a non-kosher Chinese restaurant. The rabbi can’t believe it! He watches through the window of the restaurant as the president orders food from the menu and then eats it. The rabbi can’t contain himself any longer. He barges into the restaurant and says, ‘Moshe, what are you doing? I just saw you eat that non-kosher food, and during Passover of all times! Moshes says, ‘Rabbi, did you see me enter this restaurant?’ ‘Yes!’ ‘Did you see me order the food?’ ‘Yes!’ ‘Did you see me eat the food?’ ‘Yes!’ ‘Well, then I don’t see what the problem is, Rabbi. It was all done under rabbinical supervision.’",
    "It’s been raining for days. The flood waters are rising. Moshe is on his porch, praying that the rain will stop. His neighbor stops by in a rowboat and says to Moshe, ‘We’re evacuating everyone! Get in the boat!’ Moshe replies, ‘Don’t worry about me, God will save me!’ The waters keep rising and Moshe is now on the second floor of his house. Someone comes by in a motorboat and says, ‘Moshe, get in the boat!’ Moshe replies, ‘Don’t worry about me. God will save me!’ The waters keep rising and Moshe is on the roof. A helicopter hovers overhead with a ladder and a PA system. ‘Get on the ladder! Climb into the helicopter!’ Moshe says, ‘Don’t worry about me. God will save me!’ The waters continue to rise and Moshe eventually drowns. When he finds himself in heaven, Moshe says, ‘God, I was such a faithful Jew. I kept praying that you would save me. Why didn’t you?’ God answers, ‘I sent you two boats and a helicopter. What more did you want?’",
    "Moskowitz is lying in bed at night. He can’t sleep. ‘Everything happens to me,’ he says to himself. ‘I finally get my house set up the way I like it and the landlord tells me I have to move out. I find a new place and the new landlord tells me I have to move in by tomorrow or he’s giving it away to someone else. And tonight there’s a huge blizzard! How am I going to get all my stuff to the new place tomorrow in the snow?? Wait a minute! My neighbor, Goldberg has a sled! I can borrow Goldberg’s sled! But what if Goldberg won’t lend me his sled? Not lend me his sled? I’ve been a model neighbor. I always say hello to him in the morning. I’ve lent him stuff. Of course he’s going to lend me his sled. Yeah, but people are funny. What if he won’t lend me his sled? In my hour of need, he’s not going to lend me his sled! When my life is basically over if he doesn’t lend me his sled?! Who does he think he is, not lending me his sled?’ Moskowitz gets so worked up, he puts on his boots, trudges through the snow, and bangs on Goldberg’s door at 2 a.m. Goldberg opens the door, ‘What’s going on?’ ‘Goldberg, you can keep your stinkin’ sled!’",
    "A Jewish woman is walking on the beach with her little grandson. Suddenly a huge wave sweeps the boy out to sea. Desperate, the woman looks up to heaven and says, ‘God, please rescue my grandson, my only grandson, the light of my life!’ Miraculously, the next big wave deposits the little boy at her feet, completely unharmed. She looks up to heaven and says, ‘He had a hat!’",
    "Moshe is going through a rough spot in his life. His business isn’t doing well, he’s got a bunch of kids to feed, and his wife is pressuring him. Every morning, he goes to synagogue and prays, ‘Please, God, let me win the lottery. Nothing else can fix my life like winning the lottery.’ Morning after morning after morning he prays ‘Please, God, let me win the lottery!’ Finally, he receives an answer. In the middle of his prayers, God speaks to him and says, ‘Moshe, meet me halfway. Buy a ticket!’",
    "A priest and a rabbi are sitting next to each other on a long plane ride and they get to talking. After a couple of hours, the priest says to the rabbi, ‘Tell me, Rabbi, did you ever in all your years succumb to temptation and try a little ham?’ The rabbi says, ‘You know what, Father? I will confess. I was so curious about it, I once had a ham sandwich.’ Another hour goes by and the rabbi feels comfortable enough to ask the priest, ‘Father, tell me, in all your years, did you ever succumb to temptation and see what it was like to be with a woman?’ The priest says, ‘Rabbi, I’m going to tell you the truth. Yes, one time I gave in and experienced the joys of the flesh.’ The rabbi says, ‘So, Father, beats the heck out of a ham sandwich, eh?’",
    "Sharon Leibowitz has a heart attack and is rushed to the hospital. While she’s on the operating table, her heart stops and her soul departs from her body. Sharon appears before God and asks, ‘God, is that it?’ God answers, ‘No, you have another 30 years to go, Sharon. Enjoy your life.’ Back in the operating room, the electric shocks work and Sharon regains consciousness. She’s overjoyed by her new lease on life. While she’s in the hospital, she decides to make the most of it: tummy tuck, liposuction, breast augmentation. She brings in a hair stylist, beautician, and fashion consultant for a complete makeover. When Sharon leaves the hospital, she looks spectacular. She steps out into the street, and gets run over by an ambulance and is killed instantly. Her soul goes back to heaven and again she comes before God. She says, ‘God, what happened? You told me I had another 30 years. Why didn’t you save me?’ God says, ‘Sharon, I didn’t recognize you.’",
    "An old man enters a church and goes to confession. The priest slides back the window and the old man says, ‘Forgive me, Father, for I have sinned. I’m 80 years old and earlier this week I was walking home from the library when a car pulled up with two young ladies in it. They said they were on spring break and they asked for directions. We got into a conversation and they offered me a ride home. On the way, they asked me how old I am. When they learned that I’m 80 years old, they asked “When’s the last time you had sex?” When I told them it’s been years, they asked me if I’d like to have a good time. I said sure, so they came into my apartment and for the next two nights and the day in between, hoo whee! They’re still there and they told me that when I get home, they’re going to show me things that a man and a woman can do that I never dreamed of. So that’s my confession.’ ‘I see,’ says the priest. ‘Tell me, when is the last time you made a confession?’ ‘Oh, this is my first time, Father.’ ‘You’re 80 years old and you’ve never made confession before?’ ‘No, I’m Jewish.’ ‘Well, in that case, why are you telling me all this?’ ‘Father, I’m telling everybody!’",
    "'START WORRYING. DETAILS TO FOLLOW.'",
    "A boy shows up at synagogue on Yom Kippur without a ticket and the usher won’t let him in. ‘But I’m not staying, I just need to to talk to my mother!’ ‘Okay,’ the usher says, ‘But if I catch you praying, you’re out!’",
    "A religious Jew is shipwrecked and spends thirty years on a deserted island. Finally, a passing ship sees his bonfire and sends a rescue party. Thank God, he’s getting off the island! The captain of the ship is curious how this man spent thirty years living alone, so he goes ashore and gets a tour of the island. He sees the tools, the cooking utensils, the living accommodation, etc. He asks, ‘What did you do so that you wouldn’t go insane living alone for thirty years?’ The old Jew says, ‘Let me show you.’ The pair take a little path through the jungle and come to a clearing where there is a magnificent synagogue that looks like an old European cathedral. The captain says, ‘Oh, I see. It must have taken thirty years to have built this alone by hand.’ The old Jew says, ‘No, actually it took me fifteen years. Let me show you what I did for the next fifteen.’ They take another path through the jungle to another clearing and there’s another magnificent synagogue. The captain says, ‘I understand you needed to keep busy, but two synagogues? Why?’ The old Jew says, ‘The first synagogue I pray in every day. The second synagogue, I would never step foot in that synagogue!’",
    "A guy gets on a train and settles in for an hour-long ride. There’s an old Jewish man sitting next to him who says, ‘Oy! Am I thirsty. Oy! Am I thirsty.’ The guy looks over at the old man and wonders, ‘Is this going to go on for an hour?’‘Oy! Am I thirsty.’ Realizing that it will go on, the guy reaches into his backpack, pulls out a bottle of water, and hands it to the old Jew, who drinks down the bottle. The man is quiet for about a minute and then… ‘Oy! Was I thirsty.’",
    "Back in the days when the New York Athletic Club was restricted – no Jews allowed – Milton Wasserstein wanted to join anyway, so he changed his name to Martin Waters III. He underwent surgery to give himself a less prominent nose, he traveled to England and studied with a tutor for a year to lose his accent, and, when he came back, he spent another year getting to know some members of the New York Athletic Club. Finally, it was time to come before the membership committee. The chairman asked him, ‘What is your name?’ ‘Martin Waters III.’ ‘Are you married, Mr. Waters?’ ‘Oh yes. Dorothy and I have three lovely children. Babs is our youngest, Hunter is the middle child, and Martin Waters IV is our oldest.’ ‘And your education?’ ‘The usual places – Eton, Oxford.Young Martin is there now.’ ‘Very good. And your religious affiliation?’ ‘Oh, we’re goyim, of course.’",
    "Old Saul Mankewitz is lying on his deathbed with his grandson Yossi at his side. Saul tells the boy, ‘Go down to the kitchen and get some of your grandmother’s rugelach, so that should be the last thing I taste in this world.’ Five minutes later, Yossi returns empty handed and Saul asks, ‘Where is the rugelach?’ The grandson replies, ‘Bubbe says she’s saving it for the shiva.’",

];


// Function to display a random joke
function displayJoke() {
    const jokeElement = document.getElementById('joke');
    // Generate a random index based on the length of the jokes array
    const randomIndex = Math.floor(Math.random() * jokes.length);
    // Set the joke element's text to a random joke
    jokeElement.innerText = jokes[randomIndex];
}

// Event listener for DOMContentLoaded
document.addEventListener('DOMContentLoaded', function () {
    // Initially display a random joke
    displayJoke();

    // Add click event listener to the 'new-joke' button
    document.getElementById('new-joke').addEventListener('click', function () {
        // Display a new random joke
        displayJoke();
    });
});
